//
// Autogenerated by Thrift Compiler (0.12.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//


//HELPER FUNCTIONS AND STRUCTURES

ParseRequest_parse_request_args = function(args) {
  this.r = null;
  if (args) {
    if (args.r !== undefined && args.r !== null) {
      this.r = new ClientRequest(args.r);
    }
  }
};
ParseRequest_parse_request_args.prototype = {};
ParseRequest_parse_request_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.r = new ClientRequest();
        this.r.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ParseRequest_parse_request_args.prototype.write = function(output) {
  output.writeStructBegin('ParseRequest_parse_request_args');
  if (this.r !== null && this.r !== undefined) {
    output.writeFieldBegin('r', Thrift.Type.STRUCT, 1);
    this.r.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ParseRequest_parse_request_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ServerResponse(args.success);
    }
  }
};
ParseRequest_parse_request_result.prototype = {};
ParseRequest_parse_request_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true) {
    var ret = input.readFieldBegin();
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid) {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ServerResponse();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ParseRequest_parse_request_result.prototype.write = function(output) {
  output.writeStructBegin('ParseRequest_parse_request_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

ParseRequestClient = function(input, output) {
  this.input = input;
  this.output = (!output) ? input : output;
  this.seqid = 0;
};
ParseRequestClient.prototype = {};

ParseRequestClient.prototype.parse_request = function(r, callback) {
  if (callback === undefined) {
    this.send_parse_request(r);
    return this.recv_parse_request();
  } else {
    var postData = this.send_parse_request(r, true);
    return this.output.getTransport()
      .jqRequest(this, postData, arguments, this.recv_parse_request);
  }
};

ParseRequestClient.prototype.send_parse_request = function(r, callback) {
  var params = {
    r: r
  };
  var args = new ParseRequest_parse_request_args(params);
  try {
    this.output.writeMessageBegin('parse_request', Thrift.MessageType.CALL, this.seqid);
    args.write(this.output);
    this.output.writeMessageEnd();
    return this.output.getTransport().flush(callback);
  }
  catch (e) {
    if (typeof this.output.getTransport().reset === 'function') {
      this.output.getTransport().reset();
    }
    throw e;
  }
};

ParseRequestClient.prototype.recv_parse_request = function() {
  var ret = this.input.readMessageBegin();
  var mtype = ret.mtype;
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(this.input);
    this.input.readMessageEnd();
    throw x;
  }
  var result = new ParseRequest_parse_request_result();
  result.read(this.input);
  this.input.readMessageEnd();

  if (null !== result.success) {
    return result.success;
  }
  throw 'parse_request failed: unknown result';
};
